<a href="https://colab.research.google.com/github/Tejasri-Vallakati/ML_LAB_2026-27/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
data=pd.read_csv('/content/sample_data/california_housing_train.csv')
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [17]:
data=pd.read_csv('/content/sample_data/california_housing_train.csv')
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [18]:
data.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [19]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [20]:
data.count()

longitude             17000
latitude              17000
housing_median_age    17000
total_rooms           17000
total_bedrooms        17000
population            17000
households            17000
median_income         17000
median_house_value    17000
dtype: int64

In [21]:
data.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [23]:
data.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [24]:
df3=pd.read_excel('/content/Technological-Products-Sample-Data.xlsx')
df3

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Technological Products Data,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Brand,Device,Model,Country of Origin,Date of Release,Price (USD)
5,NaN,Apple,iPhone,13 Pro Max,United States,2021-09-24 00:00:00,1099
6,NaN,Samsung,Galaxy,S21 Ultra,South Korea,2021-01-29 00:00:00,1199
7,NaN,Google,Pixel,6 Pro,United States,2021-10-19 00:00:00,899
8,NaN,Sony,PlayStation,5,Japan,2020-11-12 00:00:00,499
9,NaN,Microsoft,Surface,Laptop 4,United States,2021-04-15 00:00:00,999
10,NaN,Dell,XPS,13,United States,2021-01-28 00:00:00,999
11,NaN,HP,Spectre,x360,United States,2021-04-16 00:00:00,1349
12,NaN,Lenovo,ThinkPad,X1 Carbon,China,2021-02-15 00:00:00,1429
13,NaN,Asus,ROG,Zephyrus G14,Taiwan,2021-03-15 00:00:00,1499
14,NaN,Acer,Predator,Helios 300,Taiwan,2021-02-17 00:00:00,1299
15,NaN,Apple,MacBook,Pro 14-inch,United States,2021-10-26 00:00:00,1999
16,NaN,Samsung,Odyssey,G9,South Korea,2020-07-22 00:00:00,1699
17,NaN,Google,Pixelbook,Go,United States,2021-06-17 00:00:00,649
18,NaN,Sony,Xperia,1 III,Japan,2021-08-19 00:00:00,1299
19,NaN,Microsoft,Xbox,Series X,United States,2020-11-10 00:00:00,499
20,NaN,Dell,Alienware,m15 R5,United States,2021-04-20 00:00:00,1999
21,NaN,HP,Pavilion,x360,United States,2021-05-14 00:00:00,749
22,NaN,Lenovo,IdeaPad,5 Pro,China,2021-03-10 00:00:00,999
23,NaN,Asus,ZenBook,14,Taiwan,2021-01-15 00:00:00,799
24,NaN,Acer,Swift,3,Taiwan,2021-02-10 00:00:00,699
25,NaN,Apple,iPad,Pro 12.9-inch,United States,2021-05-21 00:00:00,1099
26,NaN,Samsung,Galaxy,Tab S7+,South Korea,2020-08-21 00:00:00,849
27,NaN,Google,Nest,Hub Max,United States,2021-03-30 00:00:00,229
28,NaN,Sony,WH,1000XM4,Malaysia,2020-08-06 00:00:00,349
29,NaN,Microsoft,Surface,Pro 8,United States,2021-10-05 00:00:00,899
30,NaN,Dell,UltraSharp,U2720Q,China,2020-12-25 00:00:00,499
31,NaN,HP,Elite,Dragonfly,United States,2021-06-28 00:00:00,1799
32,NaN,Lenovo,Legion,7i,China,2021-04-05 00:00:00,1499
33,NaN,Asus,TUF,Gaming A15,Taiwan,2021-03-20 00:00:00,1199
34,NaN,Acer,Aspire,5,Taiwan,2021-01-30 00:00:00,599

In [25]:
df3.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6'],
      dtype='object')

In [26]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      float64
 1   Unnamed: 1  33 non-null     object
 2   Unnamed: 2  31 non-null     object
 3   Unnamed: 3  31 non-null     object
 4   Unnamed: 4  31 non-null     object
 5   Unnamed: 5  31 non-null     object
 6   Unnamed: 6  31 non-null     object
dtypes: float64(1), object(6)
memory usage: 2.0+ KB

In [27]:
df3.describe()

       Unnamed: 0
count         0.0
mean          NaN
std           NaN
min           NaN
25%           NaN
50%           NaN
75%           NaN
max           NaN

In [28]:
df3.count()

Unnamed: 0     0
Unnamed: 1    33
Unnamed: 2    31
Unnamed: 3    31
Unnamed: 4    31
Unnamed: 5    31
Unnamed: 6    31
dtype: int64

In [29]:
df3.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Technological Products Data,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Brand,Device,Model,Country of Origin,Date of Release,Price (USD)

In [30]:
df3.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
30,NaN,Dell,UltraSharp,U2720Q,China,2020-12-25 00:00:00,499
31,NaN,HP,Elite,Dragonfly,United States,2021-06-28 00:00:00,1799
32,NaN,Lenovo,Legion,7i,China,2021-04-05 00:00:00,1499
33,NaN,Asus,TUF,Gaming A15,Taiwan,2021-03-20 00:00:00,1199
34,NaN,Acer,Aspire,5,Taiwan,2021-01-30 00:00:00,599